#!/bin/sh
set -eu

_VRF=
_PRIORITY=
_NETNS=
_ROUTES_IPV4=
_ROUTES_IPV6=
_LOCAL_ADDR=
_FOREIGN_ADDR=
_LOCAL_IF=
_FOREIGN_IF=

for arg in "$@"; do
	case "$arg" in
		vrf=*)
			_VRF="${arg##vrf=}"
			;;
		netns=*)
			_NETNS="${arg##netns=}"
			;;
		routes_ipv4=*)
			_ROUTES_IPV4="${arg##routes_ipv4=}"
			;;
		routes_ipv6=*)
			_ROUTES_IPV6="${arg##routes_ipv6=}"
			;;
		local_addr=*)
			_LOCAL_ADDR="${arg##local_addr=}"
			;;
		foreign_addr=*)
			_FOREIGN_ADDR="${arg##foreign_addr=}"
			;;
		local_if=*)
			_LOCAL_IF="${arg##local_if=}"
			;;
		foreign_if=*)
			_FOREIGN_IF="${arg##foreign_if=}"
			;;
		*)
			printf >&2 'Unknown option %s\n' "$arg"
			exit 1
			;;
	esac
done

if [ "" = "$_FOREIGN_IF" ]; then printf >&2 'missing foreign_if=[interface in foreign netns]\n'; exit 1; fi
if [ "" = "$_LOCAL_IF" ]; then printf >&2 'missing local_if=[interface in local netns]\n'; exit 1; fi
if [ "" = "$_LOCAL_ADDR" ]; then printf >&2 'missing local_addr=[IP addresses of local interface]\n'; exit 1; fi
if [ "" = "$_NETNS" ]; then printf >&2 'missing netns=[full path to network namespace]\n'; exit 1; fi
if [ "" = "$_VRF" ]; then printf >&2 'missing vrf=[vrf interface]; see https://docs.kernel.org/networking/vrf.html\n'; exit 1; fi
ip link add name "$_LOCAL_IF" type veth peer name "$_FOREIGN_IF" netns /proc/self/fd/3 3<"$_NETNS"
ip link set "$_LOCAL_IF" master "$_VRF"
nsenter --net="$_NETNS" sh -eu -c 'for _addr in $1; do
	ip addr add "$_addr" dev "$2"
done
ip link set "$2" address "00:00:5e:00:53:e0" up
for _route in $3; do
	ip route add "$_route" via inet6 "fe80::200:5eff:fe00:53e1" dev "$2"
done' _ "$_FOREIGN_ADDR" "$_FOREIGN_IF" "$_ROUTES_IPV4 $_ROUTES_IPV6"
sysctl -w "net/ipv4/conf/$_LOCAL_IF/rp_filter=0"
for _route in $_ROUTES_IPV4; do
	ip -4 route add local "$_route" vrf "$_VRF" dev "$_VRF"
done
for _route in $_ROUTES_IPV6; do
	ip -6 route add local "$_route" vrf "$_VRF" dev "$_VRF"
done
for _addr in $_LOCAL_ADDR; do
	ip addr add "$_addr" dev "$_LOCAL_IF"
done
ip link set "$_LOCAL_IF" address "00:00:5e:00:53:e1" up
ip -4 route add "0.0.0.0/1" via inet6 "fe80::200:5eff:fe00:53e0" vrf "$_VRF" dev "$_LOCAL_IF"
ip -4 route add "128.0.0.0/1" via inet6 "fe80::200:5eff:fe00:53e0" vrf "$_VRF" dev "$_LOCAL_IF"
ip -6 route add "::/1" via inet6 "fe80::200:5eff:fe00:53e0" vrf "$_VRF" dev "$_LOCAL_IF"
ip -6 route add "8000::/1" via inet6 "fe80::200:5eff:fe00:53e0" vrf "$_VRF" dev "$_LOCAL_IF"
